services:
  backend-nginx:
    image: nginx:1.27-alpine
    container_name: challenge-backend-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/backend
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-php

  backend-php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: challenge-backend-php
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy  
  frontend:
    image: nginx:1.27-alpine
    container_name: challenge-frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-nginx

  mysql:
    image: mysql:8.4
    container_name: challenge-mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/migrations/create.sql:/docker-entrypoint-initdb.d/01-create.sql:ro
      - ./backend/database/seeders/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s
volumes:
  mysql_data:
